-- Create table for storing face embeddings
-- This table maps PersonID to 128-dimensional face embeddings generated by FaceNet
-- Used for client-side face recognition with TensorFlow.js

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'FaceEmbeddings')
BEGIN
    CREATE TABLE dbo.FaceEmbeddings (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        PersonID INT NOT NULL,
        PhotoFileName NVARCHAR(500) NOT NULL,
        -- Store embedding as JSON array of 128 floats
        Embedding NVARCHAR(MAX) NOT NULL,
        -- Metadata
        CreatedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
        UpdatedDate DATETIME2 NOT NULL DEFAULT GETDATE(),
        -- Foreign keys
        CONSTRAINT FK_FaceEmbeddings_Person FOREIGN KEY (PersonID) 
            REFERENCES dbo.NameEvent(ID) ON DELETE CASCADE,
        CONSTRAINT FK_FaceEmbeddings_Photo FOREIGN KEY (PhotoFileName) 
            REFERENCES dbo.Pictures(PFileName) ON DELETE CASCADE
    );

    -- Index for fast person lookup
    CREATE INDEX IX_FaceEmbeddings_PersonID ON dbo.FaceEmbeddings(PersonID);
    
    -- Index for photo lookup
    CREATE INDEX IX_FaceEmbeddings_PhotoFileName ON dbo.FaceEmbeddings(PhotoFileName);
    
    PRINT 'FaceEmbeddings table created successfully';
END
ELSE
BEGIN
    PRINT 'FaceEmbeddings table already exists';
END
